apiVersion: apps/v1
kind: Deployment
metadata:
  name: invader-backtesting
  labels:
    app.name: invader-backtesting
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.name: invader-backtesting
  template:
    metadata:
      labels:
        app.name: invader-backtesting
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kops.k8s.io/instancegroup
                    operator: In
                    values:
                      - nodes-ap-southeast-1a
                      - nodes-wow-general-apse-1a
      containers:
        - name: invader-backtesting
          image: 182399701919.dkr.ecr.ap-southeast-1.amazonaws.com/invader-backtesting:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: 
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 120
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
      imagePullSecrets:
        - name: ecr-registry
      restartPolicy: Always
