apiVersion: v1
kind: Service
metadata:
  name: invader-backtesting
  labels:
    app.name: invader-backtesting
spec:
  type: NodePort
  ports:
    - name: app-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.name: invader-backtesting