name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: invader-backtesting
  KUSTOMIZE_PATH: ./deploy/prod/kustomization.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag
        id: set-tag
        run: |
          TAG=$(date +%Y%m%d)-$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "image-tag=$TAG" >> $GITHUB_OUTPUT
          echo "ECR_REPOSITORY_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}" >> $GITHUB_ENV
          echo "ecr-repository-uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kustomization with new image tag
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          cd $(dirname "${{ env.KUSTOMIZE_PATH }}")
          kustomize edit set image 338460195757.dkr.ecr.ap-southeast-1.amazonaws.com/invader-backtesting=${{ env.ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add ${{ env.KUSTOMIZE_PATH }}
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
